import type {Metadata} from "next";
import "./globals.css";
import {Toaster} from "react-hot-toast";
import AppLayout from "@/layout/app-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    <AppLayout>
      {children}
    </AppLayout>

    <Toaster
        toastOptions={{
          duration: 10000,
        }}
    />
    </body>
    </html>
  );
}
